### ISSUE TITLE
Consider making this website a fork of the original repository

### ISSUE THREAD

**Issue by ErikBoesen** [wfctest/wfctest#1]
It strikes me as a little odd to have two completely separate repositories for the same website.

**Comment by JonathanBuchh** [comment]
I made this because my mom wanted to be able to discuss changes with your dad before changing the live website. I thought making another GitHub pages site would be the easiest way for them to preview changes.

You are correct—I should have made this a fork.

**Comment by JonathanBuchh** [comment]
A fork has been created.
